baseURL: 'https://dunkloestus.github.io/Wired-Vault'
languageCode: 'en-us'
title: 'Wired Vault'
# theme: 'amethyst'  # QUITAMOS ESTA LÍNEA porque tenemos el tema directamente

# Hugo build settings
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true

# Markup settings for proper rendering
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      wikilink: true
  highlight:
    style: "github-dark"
    lineNos: true

# Main menu configuration
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Posts"
      url: "/posts/"
      weight: 2
    - name: "Notes"
      url: "/notes/"
      weight: 3
    - name: "Fixes"
      url: "/fixes/"
      weight: 4
    - name: "Tales"
      url: "/tales/"
      weight: 5
    - name: "Graph"
      url: "/graph/"
      weight: 6

# Theme parameters
params:
  # Core features
  enableToc: true
  enableBacklinks: true
  enableGraph: true
  enableSearch: true
  enableLatex: true
  enableMermaid: true
  enableFooter: true
  enableContextualBacklinks: true
  enableRecentNotes: true
  
  # Site description
  description: "Life pieces, glitches, fixes or just tales from the web or real world"
  
  # Dark theme as default
  defaultTheme: "dark"
  
  # Graph settings
  graph:
    enableGlobalGraph: true
    enableLocalGraph: true
    enableDrag: true
    enablePan: true
    enableZoom: true
    
  # Social links (customize as needed)
  social:
    github: "Dunkloestus"
    
  # Footer
  footer:
    showPoweredBy: true
    showCopyright: true

# Taxonomies
taxonomies:
  tag: tags
  category: categories

# Output formats
outputs:
  home: 
    - HTML
    - RSS
    - JSON
  page:
    - HTML
  section:
    - HTML
    - RSS
